name: Deployment workflow with WIF

on:
  workflow-dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed to be able to use the auth token from GCP auth step

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP (OIDC)
        uses: google-github-actions/auth@v0
        id: auth # Used to get the token from steps.auth.outputs in other jobs
        with:
          token_format: access_token # can also get id-token to use for authorization
          # Which provider to use for SA impersonation (projects/<gcp-project-number>/locations/global/workloadIdentityPools/<my-pool-name>/providers/<my-provider>)
          workload_identity_provider: projects/388639942010/locations/global/workloadIdentityPools/github-actions-test/providers/gha-test
          # Which SA to impersonate (aka login as)
          service_account: github-actions@gcp-competence-group.iam.gserviceaccount.com

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Cloud Run
        run: gcloud run deploy cg-gcp-example --image gcr.io/cg-gcp/example:latest --platform managed --region europe-central2
